# 05 — Otimização dos finalistas com Optuna

Neste notebook será feita a busca de ajustes finos para CatBoost, Extra Trees, HistGradientBoosting e XGBoost. A busca não será aberta para todos os modelos testados anteriormente, porque a triagem já indicou quais famílias merecem receber mais experimentos.

O Optuna será usado para explorar combinações de hiperparâmetros e uma etapa condicional de seleção de atributos. Cada tentativa será avaliada pelos mesmos cinco folds por motor usados na triagem, mantendo o holdout final fora da otimização.

In [1]:
from pathlib import Path
import sys
import optuna
import pandas as pd
import plotly.express as px
import plotly.io as pio

pio.renderers.default = 'vscode'
optuna.logging.set_verbosity(optuna.logging.WARNING)

PROJECT_ROOT = Path.cwd().resolve()
if not (PROJECT_ROOT / 'data' / 'raw' / 'dataset').exists():
    PROJECT_ROOT = Path.cwd().resolve().parents[1]
if str(PROJECT_ROOT / 'src') not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT / 'src'))

from cmapss_eda import load_split
from cmapss_modeling import add_rul_label, candidate_rul_features, nonconstant_features
from cmapss_optuna import FINALIST_NAMES, optimize_model, study_summary
from multilang import LangMap

lang = LangMap(source='pt', target='pt')
DATA_DIR = PROJECT_ROOT / 'data' / 'raw' / 'dataset'

## 1. Contrato da busca

A otimização bayesiana utiliza o histórico dos trials para concentrar novos testes em regiões promissoras do espaço de busca (Akiba et al., 2019). Em linguagem simples, os resultados anteriores são usados para evitar que todas as combinações sejam exploradas de maneira cega.

A métrica principal será o MAE médio por motor. A seleção de atributos será uma escolha condicional: o trial poderá manter todos os atributos ou aplicar `SelectKBest`, sempre ajustado dentro de cada fold. Como os quatro finalistas são modelos de árvores ou boosting, não será criado um ramo artificial de escalonamento.

In [2]:
fd001 = add_rul_label(load_split(DATA_DIR, 'train', 'FD001'))
features = nonconstant_features(fd001, candidate_rul_features())
pd.DataFrame({
    'item': ['motores', 'observações', 'atributos disponíveis', 'folds por motor', 'trials por finalista'],
    'valor': [fd001['unit'].nunique(), len(fd001), len(features), 5, 20],
})

                    item  valor
0                motores    100
1            observações  20631
2  atributos disponíveis     18
3        folds por motor      5
4   trials por finalista     20

**Insights:** A busca foi limitada a quatro famílias finalistas, com vinte trials iniciais para cada uma. O holdout oficial e qualquer divisão reservada para confirmação permanecem fora dos trials. Assim, o resultado desta etapa será usado para escolher configurações de desenvolvimento, e não para declarar desempenho final em dados ainda não vistos.

In [4]:
studies = {}
for model_name in FINALIST_NAMES:
    studies[model_name] = optimize_model(
        fd001,
        features=features,
        model_name=model_name,
        n_trials=100,
        n_splits=5,
        random_state=42,
        storage_dir=PROJECT_ROOT / 'outputs' / 'optuna',
    )
optimization_summary = study_summary(studies)
optimization_summary[['modelo', 'versao_busca', 'mae_cv_motor', 'trials', 'melhor_trial', 'status']].round(2)

                 modelo  mae_cv_motor  trials  melhor_trial    status
0           Extra Trees         25.01     100            77  COMPLETE
1               XGBoost         25.30     100             1  COMPLETE
2              CatBoost         25.35     100             2  COMPLETE
3  HistGradientBoosting         25.49     100            16  COMPLETE

### Hiperparâmetros completos dos melhores trials

Os hiperparâmetros continuam armazenados na coluna `hiperparametros`. Como strings longas são truncadas visualmente quando aparecem dentro de uma tabela larga, elas serão apresentadas abaixo em blocos separados para facilitar a conferência dos valores e dos extremos da busca.

In [ ]:
for row in optimization_summary[['modelo', 'versao_busca', 'hiperparametros']].itertuples(index=False):
    print(f'{row.modelo} — {row.versao_busca}')
    print(f'  {row.hiperparametros}')
    print()

**Insights:** O Extra Trees alcançou MAE de 25,02 ciclos, seguido por XGBoost com 25,30, CatBoost com 25,35 e HistGradientBoosting com 25,49. Em relação à triagem, os ganhos foram modestos, variando de aproximadamente 0,08 a 0,58 ciclo. Isso é coerente com a ideia de ajuste fino: a maior parte da capacidade preditiva já estava presente antes do Optuna. O melhor trial ainda representa apenas o resultado dentro do espaço e dos folds definidos.

In [5]:
fig = px.bar(
    optimization_summary,
    x='modelo',
    y='mae_cv_motor',
    labels={'modelo': 'Modelo', 'mae_cv_motor': 'Melhor MAE na CV por motor (ciclos)'},
    title=lang({'title': 'Melhor resultado encontrado pelo Optuna'})['title'],
    height=550,
)
fig.show()

**Insights:** O gráfico mostra uma vantagem pequena do Extra Trees sobre XGBoost e CatBoost, enquanto HistGradientBoosting permanece próximo. Como as diferenças são pequenas, a escolha não deverá ser feita apenas pela primeira casa decimal do MAE. Os erros por motor, a estabilidade entre folds e uma validação final separada ainda precisarão confirmar se essa ordem se mantém.

## Conclusão desta etapa

O Optuna foi usado como mecanismo de busca dentro de um contrato previamente definido. A otimização não alterou a unidade de validação, não utilizou o identificador do motor como atributo e não abriu o holdout final.

A otimização produziu uma configuração de desenvolvimento líder no Extra Trees, mas esse resultado ainda não será tratado como confirmação operacional. A próxima etapa será congelar as melhores configurações, comparar seus erros por motor e preparar uma validação final separada. Nenhum resultado desta busca será apresentado como desempenho operacional antes dessa confirmação.

## Referências

Akiba, T. et al. (2019). Optuna: A Next-generation Hyperparameter Optimization Framework. *Proceedings of the 25th ACM SIGKDD International Conference on Knowledge Discovery & Data Mining*, 2623–2631.

Pedregosa, F. et al. (2011). Scikit-learn: Machine Learning in Python. *Journal of Machine Learning Research*, 12, 2825–2830.